// @ts-nocheck
export const ZH_UI_TERMS = {
  "Literature-backed": "文献支持",
  "Benchmark-backed": "基准支持",
  "Model-predicted": "模型预测",
  "Screening proxy": "筛选代理",
  "User-defined": "用户定义",
  "Primary screening": "主要筛选",
  "Feasibility boundary": "可行性边界",
  "Shortlist comparison": "入围候选比较",
  "Future engineering evaluation": "未来工程评估",
  "Future Stage 4": "未来第 4 阶段",
  "Stage 1": "第 1 阶段",
  "Stage 2": "第 2 阶段",
  "Stage 3": "第 3 阶段",
  "Stage 2-3": "第 2-3 阶段",
  "Stage 1 screening": "第 1 阶段筛选",
  "Stage 1 interpretation": "第 1 阶段解释",
  "Stage 2 feasibility": "第 2 阶段可行性",
  "Stage 3 shortlist comparison": "第 3 阶段入围候选比较",
  "Stage 2 — Feasibility Boundaries": "第 2 阶段 — 可行性边界",
  "Stage 3 — Secondary Comparison": "第 3 阶段 — 次级比较",
  "Feasibility Boundaries": "可行性边界",
  "Feasibility boundary · exploratory only": "可行性边界 · 仅供探索",
  "Exploratory only": "仅供探索",
  "Shortlist comparison only": "仅限入围候选比较",
  "Not formal lifecycle costing": "不是正式生命周期成本",
  "Not formal LCC, not engineering-grade economics.": "不是正式 LCC，也不是工程级经济评价。",
  "Practical boundary between scientific screening and shortlist comparison.": "位于科学筛选和入围候选比较之间的实践边界。",
  "Cost / availability / supply sanity check.": "成本 / 可得性 / 供应可行性初筛。",
  "Cost / availability / supply reasonableness check.": "成本 / 可得性 / 供应可行性初筛。",
  "Cost / availability / supply feasibility screening.": "成本 / 可得性 / 供应可行性初筛。",
  "Use LCA/LCC only after an initial performance filter exists.": "仅在完成初步性能筛选后使用 LCA/LCC。",
  "Run Stage 1 first": "请先运行第 1 阶段",
  "Purpose": "用途",
  "Use stage": "使用阶段",
  "Interpretation": "解释",
  "Next layer": "下一层",
  "Stage": "阶段",
  "Source type": "来源类型",
  "Quality": "质量",
  "Limitation": "限制",
  "Basis": "依据",
  "coarse": "粗略",
  "basis": "依据",
  "proxy": "代理",
  "beta": "测试版",
  "planned": "规划中",
  "stable": "稳定",
  "calc": "计算",
  "connector scaffold": "接入脚手架",
  "benchmark-backed": "基准支持",
  "assumption-dependent": "依赖假设",
  "exploratory": "探索性",
  "comparative": "比较型",
  "future engineering-grade": "未来工程级",
  "screening prototype": "筛选级原型",
  "backend connected": "后端已连接",
  "loaded": "已加载",
  "fallback": "回退数据",
  "seed": "种子数据",
  "local seed": "本地种子",
  "screening_seed": "筛选种子",
  "reference": "参考",
  "calculated": "计算值",
  "estimated": "估算值",
  "public/data JSON + schema CSV": "public/data JSON + schema CSV",
  "sketch": "草图",
  "mentor & friend": "亦师亦友",
  "High": "高",
  "Medium": "中",
  "Low": "低",
  "Elevated": "较高",
  "Moderate": "中等",
  "Lower": "较低",
  "Custom synthesis likely": "可能需要定制合成",
  "Gram-scale or specialty supply": "克级或专用供应",
  "Likely commercially available": "可能可商业购买",
  "High rough burden": "粗略负担较高",
  "Moderate rough burden": "粗略负担中等",
  "Lower rough burden": "粗略负担较低",
  "Supplier quote / route check": "供应商报价 / 路线核查",
  "Needed before comparative LCC": "比较型 LCC 前需要补充",
  "Derived from current proxy catalog": "来自当前代理目录",
  "Stage 2 feasibility boundary": "第 2 阶段可行性边界",
  "Linker": "连接体",
  "Availability": "可得性",
  "Material burden note": "材料负担提示",
  "Next evidence": "下一步证据",
  "Very Low": "很低",
  "Open metal site": "开放金属位点",
  "CoRE MOF 2019 + NIST isotherms": "CoRE MOF 2019 + NIST 等温线",
  "CoRE MOF 2019 — broad GCMC coverage": "CoRE MOF 2019 — GCMC 覆盖较广",
  "π-complexation MOF literature": "π 配位 MOF 文献",
  "Anomalous inverse selectivity reported": "已有反常反向选择性报道",
  "Classical model; quantum diffusion not yet corrected": "经典模型；尚未修正量子扩散",
  "Public GCMC data scarce; honest gap acknowledged in v1.β.": "公开 GCMC 数据稀缺；v1.β 明确标注该缺口。",
  "Lewis-basic / H-bond donor": "Lewis 碱性 / 氢键供体",
  "H-bond donor": "氢键供体",
  "H-bond donor/acceptor": "氢键供体/受体",
  "Soft donor (S)": "软供体（S）",
  "Electron-withdrawing": "吸电子基团",
  "Electron-withdrawing / polar": "吸电子 / 极性",
  "Electron-withdrawing / halogen": "吸电子 / 卤素",
  "Electron-withdrawing / heavy": "吸电子 / 重卤素",
  "Heavy halogen / polarizable": "重卤素 / 易极化",
  "Steric / hydrophobic": "位阻 / 疏水",
  "Strong electron-withdrawing / hydrophobic": "强吸电子 / 疏水",
  "Bulky hydrophobic substituent": "大位阻疏水取代基",
  "Weak H-bond acceptor": "弱氢键受体",
  "Lewis-basic (aromatic N)": "Lewis 碱性（芳香 N）",
  "Ditopic carboxylate": "二连接羧酸配体",
  "Ditopic carboxylate+OH": "二连接羧酸 + 羟基配体",
  "Tritopic carboxylate": "三连接羧酸配体",
  "Tetratopic porphyrin": "四连接卟啉配体",
  "Tetratopic carboxylate": "四连接羧酸配体",
  "Ditopic azolate": "二连接唑类配体",
  "Strong": "强",
  "Stable": "稳定",
  "Sensitive": "敏感",
  "Completed": "已完成",
  "Top candidate": "最高候选",
  "Average selectivity": "平均选择性",
  "Exportable runs": "可导出记录",
  "Best selectivity": "最高选择性",
  "Best eco score": "最高生态评分",
  "Adjusted LCC": "调整后 LCC",
  "Adjusted eco score": "调整后生态评分",
  "Custom LCA score": "自定义 LCA 评分",
  "Custom LCC": "自定义 LCC",
  "P05 / P50 / P95": "P05 / P50 / P95",
  "API connected": "API 已连接",
  "static fallback": "静态回退",
  "Browser profile or optional backend prediction.": "浏览器模型配置或可选后端预测。",
  "Seed benchmark + descriptor input": "种子基准 + 描述符输入",
  "Applicability warning present.": "存在适用域警告。",
  "Within prototype descriptor range.": "位于原型描述符范围内。",
  "Screening-level only": "仅限筛选级",
  "Not a strict IAST/GCMC or experimental result.": "不是严格 IAST/GCMC 或实验结果。",
  "Medium-low": "中低",
  "Apparent": "表观",
  "Henry proxy": "Henry 代理",
  "IAST proxy": "IAST 代理",
  "Method": "方法",
  "Importance": "重要性",
  "EXCELLENT": "优秀",
  "GOOD": "良好",
  "FAIR": "一般",
  "POOR": "较差",
  "Retraining": "真实训练",
  "front-end profile": "前端配置",
  "transparent status": "透明状态说明",
  "static": "静态",
  "static site": "静态站点",
  "local screening model": "本地筛选模型",
  "public seed": "公开种子数据",
  "Manifest source": "清单来源",
  "Model status": "模型状态",
  "Training origin": "训练来源",
  "Rows": "训练行数",
  "Targets": "目标变量",
  "No API URL set; using local screening model.": "未设置 API 地址；使用本地筛选模型。",
  "Backend prediction used for this run.": "本次运行使用后端预测。",
  "Local screening model": "本地筛选模型",
  "Parameter": "参数",
  "Value": "数值",
  "Control": "控制",
  "Flow": "流",
  "Unit": "单位",
  "Replacement": "替换路线",
  "LCA/LCC inventory seed": "LCA/LCC 清单种子数据",
  "public/data/lca_inventory.json with source fields.": "public/data/lca_inventory.json，含来源字段。",
  "Traceable schema, not full industrial LCI.": "可追溯 schema，但不是完整工业 LCI。",
  "Exploratory, assumption-dependent, and not engineering-grade.": "探索性、依赖假设，且不是工程级。",
  "Use only after Stage 1 screening and Stage 2 feasibility boundaries.": "仅在第 1 阶段筛选和第 2 阶段可行性边界之后使用。",
  "Performance": "性能",
  "Adsorption performance": "吸附性能",
  "LCA burden": "LCA 负担",
  "Current MOF": "当前 MOF",
  "Low energy": "低能耗",
  "High recovery": "高回收",
  "Conservative": "保守情景",
  "Base": "基准情景",
  "license": "许可",
  "records": "条记录",
  "Current implementation status": "当前实现状态",
  "What retrained models would add": "重训模型会增加什么",
}
