export const DESCRIPTOR_REGISTRY = {
  surfaceArea: {
    key: "surfaceArea",
    label: "Surface area",
    labelZh: "比表面积",
    unit: "m²/g",
    group: "porosity",
    valueType: "number",
    direction: "benefit",
    defaultRole: "scoring",
    sourceField: "surfaceArea",
    evidenceRequired: true,
    missingPolicy: "warn",
    normalizer: "minmax",
    defaultRange: [300, 3000],
    description: "Accessible surface area proxy for adsorption and interaction capacity.",
    descriptionZh: "用于表征吸附与相互作用容量的可达比表面积线索。",
    planned: false,
  },
  poreSizeA: {
    key: "poreSizeA",
    label: "Pore size",
    labelZh: "孔径",
    unit: "Å",
    group: "porosity",
    valueType: "number",
    direction: "benefit",
    defaultRole: "scoring",
    sourceField: "poreSizeA",
    evidenceRequired: true,
    missingPolicy: "warn",
    normalizer: "minmax",
    defaultRange: [3, 30],
    description: "Representative pore aperture for molecular accessibility.",
    descriptionZh: "用于判断分子可达性的代表性孔径。",
    planned: false,
  },
  poreVolume: {
    key: "poreVolume",
    label: "Pore volume",
    labelZh: "孔体积",
    unit: "cm³/g",
    group: "porosity",
    valueType: "number",
    direction: "benefit",
    defaultRole: "scoring",
    sourceField: "poreVolume",
    evidenceRequired: true,
    missingPolicy: "warn",
    normalizer: "minmax",
    defaultRange: [0.2, 1.8],
    description: "Void volume proxy for capacity and transport space.",
    descriptionZh: "用于表征容量与传质空间的孔体积线索。",
    planned: false,
  },
  co2Uptake: {
    key: "co2Uptake",
    label: "CO₂ uptake",
    labelZh: "CO₂ 吸附量",
    unit: "mmol/g",
    group: "adsorption",
    valueType: "number",
    direction: "benefit",
    defaultRole: "scoring",
    sourceField: "co2Uptake",
    evidenceRequired: true,
    missingPolicy: "warn",
    normalizer: "minmax",
    defaultRange: [0, 10],
    description: "Early adsorption capacity indicator; condition context remains required.",
    descriptionZh: "早期吸附容量指标，仍需要条件上下文。",
    planned: false,
  },
  bandGap: {
    key: "bandGap",
    label: "Band gap",
    labelZh: "带隙",
    unit: "eV",
    group: "electronic",
    valueType: "number",
    direction: "benefit",
    defaultRole: "scoring",
    sourceField: "bandGap",
    evidenceRequired: true,
    missingPolicy: "warn",
    normalizer: "minmax",
    defaultRange: [0.5, 5],
    description: "Electronic descriptor used here as an exploratory screening cue.",
    descriptionZh: "此处作为探索性筛选线索的电子结构描述符。",
    planned: false,
  },
  waterStability: {
    key: "waterStability",
    label: "Water stability",
    labelZh: "水稳定性",
    unit: "",
    group: "stability",
    valueType: "ordinal",
    direction: "benefit",
    defaultRole: "scoring",
    sourceField: "waterStability",
    evidenceRequired: true,
    missingPolicy: "warn",
    normalizer: "categoricalScore",
    levels: { low: 0.2, medium: 0.58, high: 1, unknown: null },
    description: "Qualitative or curated stability under aqueous exposure.",
    descriptionZh: "水相暴露下的定性或已整理稳定性线索。",
    planned: false,
  },
  thermalStability: {
    key: "thermalStability",
    label: "Thermal stability",
    labelZh: "热稳定性",
    unit: "",
    group: "stability",
    valueType: "ordinal",
    direction: "benefit",
    defaultRole: "scoring",
    sourceField: "thermalStability",
    evidenceRequired: true,
    missingPolicy: "warn",
    normalizer: "categoricalScore",
    levels: { low: 0.2, medium: 0.58, high: 1, unknown: null },
    description: "Thermal robustness cue from TGA, literature, or curation state.",
    descriptionZh: "来自 TGA、文献或整理状态的热稳定性线索。",
    planned: false,
  },
  toxicityConcern: {
    key: "toxicityConcern",
    label: "Toxicity concern",
    labelZh: "毒性关注",
    unit: "",
    group: "sustainability",
    valueType: "ordinal",
    direction: "cost",
    defaultRole: "scoring",
    sourceField: "toxicityConcern",
    evidenceRequired: true,
    missingPolicy: "warn",
    normalizer: "categoricalScore",
    levels: { low: 0.15, medium: 0.55, high: 1, unknown: null },
    description: "Cost-style risk descriptor; lower concern should improve the score.",
    descriptionZh: "cost-style 风险描述符；毒性关注越低越支持排序。",
    planned: false,
  },
  synthesisTemperature: {
    key: "synthesisTemperature",
    label: "Synthesis temperature",
    labelZh: "合成温度",
    unit: "°C",
    group: "synthesis",
    valueType: "number",
    direction: "cost",
    defaultRole: "warning",
    sourceField: "synthesisTemperature",
    evidenceRequired: true,
    missingPolicy: "ignore",
    normalizer: "minmax",
    defaultRange: [20, 250],
    description: "Planned synthesis burden descriptor for future process-aware screening.",
    descriptionZh: "面向后续工艺负担筛选的预留合成描述符。",
    planned: true,
  },
  synthesisTime: {
    key: "synthesisTime",
    label: "Synthesis time",
    labelZh: "合成时间",
    unit: "h",
    group: "synthesis",
    valueType: "number",
    direction: "cost",
    defaultRole: "warning",
    sourceField: "synthesisTime",
    evidenceRequired: true,
    missingPolicy: "ignore",
    normalizer: "minmax",
    defaultRange: [1, 168],
    description: "Planned synthesis duration descriptor.",
    descriptionZh: "预留的合成时长描述符。",
    planned: true,
  },
  precursorCost: {
    key: "precursorCost",
    label: "Precursor cost",
    labelZh: "前驱体成本",
    unit: "relative",
    group: "sustainability",
    valueType: "number",
    direction: "cost",
    defaultRole: "warning",
    sourceField: "precursorCost",
    evidenceRequired: true,
    missingPolicy: "ignore",
    normalizer: "robustMinmax",
    defaultRange: [0, 100],
    description: "Planned cost descriptor for synthesis feasibility.",
    descriptionZh: "用于后续合成可行性判断的预留成本描述符。",
    planned: true,
  },
  solventConcern: {
    key: "solventConcern",
    label: "Solvent concern",
    labelZh: "溶剂关注",
    unit: "relative",
    group: "sustainability",
    valueType: "ordinal",
    direction: "cost",
    defaultRole: "warning",
    sourceField: "solventConcern",
    evidenceRequired: true,
    missingPolicy: "ignore",
    normalizer: "categoricalScore",
    levels: { low: 0.15, medium: 0.55, high: 1, unknown: null },
    description: "Planned solvent safety and environmental concern descriptor.",
    descriptionZh: "预留的溶剂安全与环境关注描述符。",
    planned: true,
  },
  selectivity: {
    key: "selectivity",
    label: "Selectivity",
    labelZh: "选择性",
    unit: "relative",
    group: "adsorption",
    valueType: "number",
    direction: "benefit",
    defaultRole: "scoring",
    sourceField: "selectivity",
    evidenceRequired: true,
    missingPolicy: "warn",
    normalizer: "minmax",
    defaultRange: [0, 120],
    description: "Planned adsorption selectivity descriptor for focused screening presets.",
    descriptionZh: "用于后续吸附导向预设的选择性描述符。",
    planned: true,
  },
  regenerationEnergy: {
    key: "regenerationEnergy",
    label: "Regeneration energy",
    labelZh: "再生能耗",
    unit: "relative",
    group: "sustainability",
    valueType: "number",
    direction: "cost",
    defaultRole: "warning",
    sourceField: "regenerationEnergy",
    evidenceRequired: true,
    missingPolicy: "ignore",
    normalizer: "robustMinmax",
    defaultRange: [0, 100],
    description: "Planned energy burden descriptor for adsorption cycle evaluation.",
    descriptionZh: "用于后续吸附循环评价的预留能耗描述符。",
    planned: true,
  },
  lifecycleGwp: {
    key: "lifecycleGwp",
    label: "Lifecycle GWP",
    labelZh: "生命周期 GWP",
    unit: "kg CO₂-eq",
    group: "sustainability",
    valueType: "number",
    direction: "cost",
    defaultRole: "warning",
    sourceField: "lifecycleGwp",
    evidenceRequired: true,
    missingPolicy: "ignore",
    normalizer: "robustMinmax",
    defaultRange: [0, 100],
    description: "Planned lifecycle climate-impact descriptor.",
    descriptionZh: "预留的生命周期气候影响描述符。",
    planned: true,
  },
  lifecyclePed: {
    key: "lifecyclePed",
    label: "Lifecycle PED",
    labelZh: "生命周期 PED",
    unit: "MJ",
    group: "sustainability",
    valueType: "number",
    direction: "cost",
    defaultRole: "warning",
    sourceField: "lifecyclePed",
    evidenceRequired: true,
    missingPolicy: "ignore",
    normalizer: "robustMinmax",
    defaultRange: [0, 100],
    description: "Planned primary-energy demand descriptor.",
    descriptionZh: "预留的一次能源需求描述符。",
    planned: true,
  },
  d_stab: {
    key: "d_stab",
    label: "Hydrothermal stability",
    labelZh: "水热稳定性",
    unit: "",
    group: "catalysis",
    valueType: "number",
    direction: "benefit",
    defaultRole: "scoring",
    sourceField: "d_stab",
    evidenceRequired: true,
    missingPolicy: "penalize",
    normalizer: "minmax",
    defaultRange: [0, 1],
    description: "Formate-pathway stability descriptor retained for the catalysis CRITIC preview.",
    descriptionZh: "产甲酸路径 CRITIC preview 保留的稳定性描述符。",
    planned: false,
  },
  d_barrier: {
    key: "d_barrier",
    label: "Formate barrier support",
    labelZh: "甲酸路径能垒支持",
    unit: "",
    group: "catalysis",
    valueType: "number",
    direction: "benefit",
    defaultRole: "scoring",
    sourceField: "d_barrier",
    evidenceRequired: true,
    missingPolicy: "penalize",
    normalizer: "minmax",
    defaultRange: [0, 1],
    description: "Benefit-style formate-pathway barrier descriptor.",
    descriptionZh: "benefit-style 产甲酸路径能垒描述符。",
    planned: false,
  },
  d_select: {
    key: "d_select",
    label: "Byproduct-risk support",
    labelZh: "副产物风险支持",
    unit: "",
    group: "catalysis",
    valueType: "number",
    direction: "benefit",
    defaultRole: "scoring",
    sourceField: "d_select",
    evidenceRequired: true,
    missingPolicy: "penalize",
    normalizer: "minmax",
    defaultRange: [0, 1],
    description: "Benefit-style descriptor after converting byproduct risk into selectivity support.",
    descriptionZh: "将副产物风险转换为选择性支持后的 benefit-style 描述符。",
    planned: false,
  },
}

export const CORE_MOF_DESCRIPTOR_KEYS = [
  "surfaceArea",
  "poreSizeA",
  "poreVolume",
  "co2Uptake",
  "bandGap",
  "waterStability",
  "thermalStability",
  "toxicityConcern",
]

export const PLANNED_DESCRIPTOR_KEYS = [
  "synthesisTemperature",
  "synthesisTime",
  "precursorCost",
  "solventConcern",
  "selectivity",
  "regenerationEnergy",
  "lifecycleGwp",
  "lifecyclePed",
]

export function getDescriptor(key) {
  return DESCRIPTOR_REGISTRY[key] || null
}

export function getDescriptors(keys = Object.keys(DESCRIPTOR_REGISTRY)) {
  return (Array.isArray(keys) ? keys : [])
    .map(key => (typeof key === "object" && key?.key ? { ...getDescriptor(key.key), ...key } : getDescriptor(key)))
    .filter(Boolean)
}

export function getAllDescriptors({ includePlanned = true } = {}) {
  return getDescriptors(Object.keys(DESCRIPTOR_REGISTRY)).filter(descriptor => includePlanned || !descriptor.planned)
}

export function getDescriptorsByGroup(group, options = {}) {
  return getAllDescriptors(options).filter(descriptor => descriptor.group === group)
}
