export function organicAcidCandidate(overrides = {}) {
  return {
    id: "OA_REAL_001",
    displayName: "Al-formate-ready scaffold",
    sourceDatabase: "Curated Organic Acid source",
    sourceRecordId: "OA-REAL-001",
    metals: ["Al"],
    frameworkType: "Al-O chain",
    topology: "mil-53-like",
    pldA: 5.1,
    poreVolume: 0.42,
    surfaceArea: 980,
    sourceConfirmed: true,
    citationReady: true,
    verifiedMetadata: true,
    hydrothermalGate: { status: "pass" },
    organicAcidScore: { evidenceLevel: "high", collapseRisk: 0.16 },
    descriptorScores: {
      hydrothermalEvidenceStrength: 0.86,
      thermalStability: 0.8,
      waterBlockingResistance: 0.76,
      poreAccessibility: 0.82,
      c1IntermediateAccessibility: 0.84,
      alOFrameworkRobustness: 0.86,
      linkerMicroenvironmentMatch: 0.78,
      evidenceConfidence: 0.82,
      collapseRisk: 0.16,
    },
    fieldSources: {
      sourceDatabase: { sourceType: "curated_real", curationStatus: "source_confirmed", confidence: 0.8 },
      poreSizeA: { sourceType: "curated_real", curationStatus: "confirmed", confidence: 0.8 },
      collapseRisk: { sourceType: "derived_proxy", curationStatus: "reviewed", confidence: 0.72 },
    },
    dataStatus: { level: "curated_real", verified: true },
    evidenceIds: ["EVID-REAL-001"],
    ...overrides,
  }
}

export function organicAcidFixtureCandidates() {
  return [
    organicAcidCandidate(),
    organicAcidCandidate({
      id: "OA_LOW_EVIDENCE",
      displayName: "Low evidence high pathway scaffold",
      verifiedMetadata: false,
      citationReady: false,
      organicAcidScore: { evidenceLevel: "very low", collapseRisk: 0.2 },
      descriptorScores: {
        hydrothermalEvidenceStrength: 0.72,
        thermalStability: 0.7,
        waterBlockingResistance: 0.7,
        poreAccessibility: 0.9,
        c1IntermediateAccessibility: 0.92,
        alOFrameworkRobustness: 0.72,
        linkerMicroenvironmentMatch: 0.9,
        evidenceConfidence: 0.18,
        collapseRisk: 0.2,
      },
      fieldSources: { sourceDatabase: { sourceType: "curated_real", curationStatus: "needs_review", confidence: 0.4 } },
      dataStatus: { level: "curated_real", verified: false },
    }),
    organicAcidCandidate({
      id: "OA_RISKY",
      displayName: "Collapse-risk scaffold",
      hydrothermalGate: { status: "fail" },
      organicAcidScore: { evidenceLevel: "medium", collapseRisk: 0.88 },
      descriptorScores: {
        hydrothermalEvidenceStrength: 0.2,
        thermalStability: 0.25,
        waterBlockingResistance: 0.35,
        poreAccessibility: 0.74,
        c1IntermediateAccessibility: 0.7,
        alOFrameworkRobustness: 0.24,
        linkerMicroenvironmentMatch: 0.62,
        evidenceConfidence: 0.5,
        collapseRisk: 0.88,
      },
    }),
    organicAcidCandidate({
      id: "OA_SYNTHETIC",
      displayName: "Synthetic demo scaffold",
      sourceDatabase: "Demo / synthetic fixture",
      sourceRecordId: "OA-DEMO-001",
      verifiedMetadata: false,
      citationReady: false,
      dataStatus: { level: "demo_proxy", verified: false },
    }),
  ]
}
