// Barrel re-exports — import everything shared from this one file
export * from "./contexts"
export * from "./constants/theme"
export * from "./constants/catalogs"
export * from "./constants/defaults"
export * from "./constants/uiTerms"
export * from "./constants/badges"
export * from "./utils/functionalGroups"
export * from "./utils/presets"
export * from "./utils/cif"
export * from "./utils/isotherm"
export * from "./utils/prediction"
export * from "./utils/labels"
export * from "./utils/report"
export * from "./utils/styles"
export * from "./components/ui"
export * from "./components/layout"
